// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8H7FNFyTQHjKl4GS6hDbdyON-6epjFiU',
    appId: '1:888997423329:web:29373886bfc719724e6fa0',
    messagingSenderId: '888997423329',
    projectId: 'gh-myapp-flutter-2946c',
    authDomain: 'gh-myapp-flutter-2946c.firebaseapp.com',
    storageBucket: 'gh-myapp-flutter-2946c.appspot.com',
    measurementId: 'G-Z19SMRRHQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZasB3rebQa3mhw4PhccMXNUvnxeUScqo',
    appId: '1:888997423329:android:b340bd46170da2f54e6fa0',
    messagingSenderId: '888997423329',
    projectId: 'gh-myapp-flutter-2946c',
    storageBucket: 'gh-myapp-flutter-2946c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIw6Rjsq1UR8BEb4yJuQx0d7l4LByqVs',
    appId: '1:888997423329:ios:9f4ba7cb601cfb2e4e6fa0',
    messagingSenderId: '888997423329',
    projectId: 'gh-myapp-flutter-2946c',
    storageBucket: 'gh-myapp-flutter-2946c.appspot.com',
    iosClientId: '888997423329-s08e9dhcuctg7qd5kt53aud0lefm256q.apps.googleusercontent.com',
    iosBundleId: 'dev.gh.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVIw6Rjsq1UR8BEb4yJuQx0d7l4LByqVs',
    appId: '1:888997423329:ios:9f4ba7cb601cfb2e4e6fa0',
    messagingSenderId: '888997423329',
    projectId: 'gh-myapp-flutter-2946c',
    storageBucket: 'gh-myapp-flutter-2946c.appspot.com',
    iosClientId: '888997423329-s08e9dhcuctg7qd5kt53aud0lefm256q.apps.googleusercontent.com',
    iosBundleId: 'dev.gh.myapp',
  );
}
